module.exports = {
  "C1":{note:"C"},
  "Csharp1":{note:"C#"},
  "D1":{note:"D"},
  "Dsharp1":{note:"D#"},
  "E1":{note:"E"},
  "F1":{note:"F"},
  "Fsharp1":{note:"F#"},
  "G1":{note:"G"},
  "Gsharp1":{note:"G#"},
  "A1":{note:"A"},
  "Asharp1":{note:"A#"},
  "B1":{note:"B"},
  "C2":{note:"C"},
  "Csharp2":{note:"C#"},
  "D2":{note:"D"},
  "Dsharp2":{note:"D#"},
  "E2":{note:"E"},
  "F2":{note:"F"},
  "Fsharp2":{note:"F#"},
  "G2":{note:"G"},
  "Gsharp2":{note:"G#"},
  "A2":{note:"A"},
  "Asharp2":{note:"A#"},
  "B2":{note:"B"},
  "C3":{note:"C"},
  "Csharp3":{note:"C#"},
  "D3":{note:"D"},
  "Dsharp3":{note:"D#"},
  "E3":{note:"E"},
  "F3":{note:"F"},
  "Fsharp3":{note:"F#"},
  // "G3":{note:"G"},
  // "Gsharp3":{note:"G#"},
  // "A3":{note:"A"},
  // "Asharp3":{note:"A#"},
  // "B3":{note:"B"},
};
